language: ruby

matrix:
  include:
    # default build
    - { rvm: 2.2.3, gemfile: gemfiles/activerecord_4_2.gemfile, env: DB=postgres  }

    # different databases
    - { rvm: 2.2.3, gemfile: gemfiles/activerecord_4_2.gemfile, env: DB=mysql     }

    # different ruby versions
    - { rvm: 2.1.1, gemfile: gemfiles/activerecord_4_2.gemfile, env: DB=postgres  }
    - { rvm: 2.2.3, gemfile: gemfiles/activerecord_4_2.gemfile, env: DB=postgres  }
    - { rvm: 2.3.3, gemfile: gemfiles/activerecord_4_2.gemfile, env: DB=postgres  }

    # different activerecord versions
    - { rvm: 2.2.3, gemfile: gemfiles/activerecord_4_2.gemfile, env: DB=postgres  }
    - { rvm: 2.3.3, gemfile: gemfiles/activerecord_5_0.gemfile, env: DB=postgres  }

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database if not exists oauth2_test;'; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database oauth2_test;' -U postgres; fi"
